**Nome:** Maria Luiza Pinheiro Ferreira **DRE:** 124167281

**Nome:** Betina de Mattos Vieira Matis Pereira **DRE:** 124054006

# **Questão 1:**

In [1]:
import numpy as np

def caractere_para_numero(c):
    c = c.lower()
    if c == ' ':
        return 0
    elif 'a' <= c <= 'z':
        return ord(c) - ord('a') + 1
    else:
        return 0

def criar_matriz(n):
    """
    Gera a matriz A de codificação (n×n) invertível:
    A = 2·I + J, onde I é a identidade e J é a matriz de 1.
    """
    I = np.eye(n, dtype=int)
    J = np.ones((n, n), dtype=int)
    return 2 * I + J


def codificar_mensagem(mensagem):
    """
    Codifica a mensagem em um vetor b̄:

    """
    # Limita em 10 caracteres e garante tamanho mínimo de 3
    if len(mensagem) > 10:
        raise ValueError("Mensagem deve ter no máximo 10 caracteres.")
    mensagem = mensagem[:10]
    n = max(3, len(mensagem))

    # Converte para vetor numérico e preenche com zeros
    b = np.array([ caractere_para_numero(c) for c in mensagem], dtype=int)
    if b.shape[0] < n:
        b = np.pad(b, (0, n - b.shape[0]), mode='constant', constant_values=0)

    # Gera matriz e calcula codificado
    A = criar_matriz(n)
    b_linha = A.dot(b)

    return A, b_linha


def main():
    mensagem = input("Digite uma mensagem de até 10 caracteres: ")
    A, b_linha = codificar_mensagem(mensagem)

    print(f"\nMatriz A ({A.shape[0]}×{A.shape[1]}):")
    print(A)
    print("\nVetor codificado b̄:")
    print(b_linha)


if __name__ == "__main__":
    main()


Matriz A (7×7):
[[3 1 1 1 1 1 1]
 [1 3 1 1 1 1 1]
 [1 1 3 1 1 1 1]
 [1 1 1 3 1 1 1]
 [1 1 1 1 3 1 1]
 [1 1 1 1 1 3 1]
 [1 1 1 1 1 1 3]]

Vetor codificado b̄:
[ 99  87  69 113  99  75  79]


# **Questão 2:**

In [2]:
import numpy as np

def numero_para_caractere(num):
    """
    Converte número para caractere:

    """
    if num == 0:
        return ' '
    if 1 <= num <= 26:
        return chr(ord('a') + int(num) - 1)
    return ' '

def criar_matriz(n):
    """
    Gera a matriz A = 2·I + J de dimensão n×n.

    """
    I = np.eye(n, dtype=float)
    J = np.ones((n, n), dtype=float)
    return 2 * I + J

def inverter_matriz(A):
    """
    Inverte a matriz A usando eliminação de Gauss-Jordan.

    """
    n = A.shape[0]
    aug = np.hstack((A.copy(), np.eye(n)))
    for i in range(n):
        # Pivotamento parcial
        linha_max = np.argmax(np.abs(aug[i:, i])) + i
        if aug[linha_max, i] == 0:
            raise ValueError("Matriz singular, não é possível inverter.")
        if linha_max != i:
            aug[[i, linha_max]] = aug[[linha_max, i]]
        # Normaliza pivô
        aug[i] /= aug[i, i]
        # Elimina coluna i nas outras linhas
        for j in range(n):
            if j != i:
                aug[j] -= aug[j, i] * aug[i]
    return aug[:, n:]

def main():
    entrada = input("Digite os valores de b̄ separados por espaço: ")
    try:
        b_linha = np.array([float(x) for x in entrada.split()])
    except ValueError:
        print("Erro: entrada inválida. Use números separados por espaço.")
        return

    m = b_linha.size
    if m < 3:
        print("Erro: número de elementos deve ser no mínimo 3.")
        return
    if m > 10:
        print("Erro: número de elementos deve ser no máximo 10.")
        return
    n = m

    # Reconstrói A e calcula inversa
    A = criar_matriz(n)
    try:
        A_inv = inverter_matriz(A)
    except ValueError as e:
        print(e)
        return

    # Recupera b
    b = A_inv.dot(b_linha)
    b_int = np.rint(b).astype(int)
    mensagem = ''.join(numero_para_caractere(x) for x in b_int)

    print("\nMensagem decodificada:")
    print(mensagem)

if __name__ == "__main__":
    main()



Mensagem decodificada:
oi voce
